#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.box = "debian-8.1-amd64-lxc-puppet-docker"
 config.vm.box_url = "https://dl.dropboxusercontent.com/u/3523744/boxes/debian-8.1-amd64-lxc-puppet-docker/debian-8.1-amd64-lxc-puppet-docker.box"

 config.vm.provider "virtualbox" do |v|
   v.memory = 1024
   v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
 end

 config.vm.synced_folder "../demo-site/", "/external/demo-site"
 config.vm.synced_folder "../architecture/", "/external/architecture"
 config.vm.synced_folder "../database/", "/external/database"
 config.vm.synced_folder "../dsl/", "/external/dsl"
 config.vm.synced_folder "../dashboard/", "/external/dashboard"
 config.vm.synced_folder "../core-os/", "/external/core-os"

 config.vm.define "busdevops-dev-machine" do |busdevopsdevmachine|
   busdevopsdevmachine.vm.network "private_network", ip: "33.33.33.60"
   busdevopsdevmachine.vm.provision "puppet" do |puppet|
    puppet.manifest_file = ""
  end
 end

end
